--
-- Script was generated by Devart dbForge Studio 2021 for SQL Server, Version 6.0.563.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 16/09/2024 12:23:19 am
-- Server version: 15.00.4385
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
USE master
GO

IF DB_NAME() <> N'master' SET NOEXEC ON

--
-- Create database [ProductManagement]
--
PRINT (N'Create database [ProductManagement]')
GO
CREATE DATABASE ProductManagement
ON PRIMARY(
    NAME = N'ProductManagement',
    FILENAME = N'/var/opt/mssql/data/ProductManagement.mdf',
    SIZE = 8192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
)
LOG ON(
    NAME = N'ProductManagement_log',
    FILENAME = N'/var/opt/mssql/data/ProductManagement_log.ldf',
    SIZE = 8192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
)
GO

--
-- Alter database
--
PRINT (N'Alter database')
GO
ALTER DATABASE ProductManagement
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS OFF,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK OFF,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    COMPATIBILITY_LEVEL = 150,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT OFF,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    DB_CHAINING OFF,
    HONOR_BROKER_PRIORITY OFF,
    MULTI_USER,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT OFF,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF,
    TRANSFORM_NOISE_WORDS = OFF,
    TRUSTWORTHY OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE ProductManagement
  SET ENABLE_BROKER
GO

ALTER DATABASE ProductManagement
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

EXECUTE sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
EXECUTE sp_configure 'nested triggers', 1;
GO
RECONFIGURE;
GO

ALTER DATABASE ProductManagement
  SET QUERY_STORE = OFF
GO

USE ProductManagement
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE ProductManagement
GO

IF DB_NAME() <> N'ProductManagement' SET NOEXEC ON
GO

--
-- Create table [dbo].[Product]
--
PRINT (N'Create table [dbo].[Product]')
GO
CREATE TABLE dbo.Product (
  ID uniqueidentifier NOT NULL,
  Name nvarchar(255) NOT NULL,
  Price decimal(38) NULL DEFAULT (0),
  CategoryID uniqueidentifier NOT NULL,
  CONSTRAINT Product_PK PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT Product_UNIQUE_Name UNIQUE (Name)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Category]
--
PRINT (N'Create table [dbo].[Category]')
GO
CREATE TABLE dbo.Category (
  ID uniqueidentifier NOT NULL,
  Name nvarchar(255) NOT NULL,
  CONSTRAINT PK_Category_ID PRIMARY KEY CLUSTERED (ID),
  CONSTRAINT Category_UNIQUE_Name UNIQUE (Name)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table Product
--
PRINT (N'Dumping data for table Product')
INSERT dbo.Product VALUES ('7b70509e-e19f-487d-bdc5-2e138f45f71a', N'Quần jeans', 100000, '79118eaa-05c6-40aa-989e-e471580d9cfd')
INSERT dbo.Product VALUES ('cb526d55-77cc-4d1f-9d35-4405eee65416', N'Áo sơ mi tay cụt ngắn', 120000, '3206fdaa-c0c8-49e6-920a-c9b8f2eb08fc')
INSERT dbo.Product VALUES ('58da7c6c-5aba-4410-9675-4afcedabc836', N'Áo thun', 100000, '3206fdaa-c0c8-49e6-920a-c9b8f2eb08fc')
INSERT dbo.Product VALUES ('20cdfc86-2eb3-4061-98d3-58357b2ac936', N'Áo khoác', 200000, '3206fdaa-c0c8-49e6-920a-c9b8f2eb08fc')
INSERT dbo.Product VALUES ('49f5375a-da0a-4285-81b7-b4757969787a', N'Áo sơ mi', 120000, '3206fdaa-c0c8-49e6-920a-c9b8f2eb08fc')
GO

-- 
-- Dumping data for table Category
--
PRINT (N'Dumping data for table Category')
INSERT dbo.Category VALUES ('3206fdaa-c0c8-49e6-920a-c9b8f2eb08fc', N'Áooo')
INSERT dbo.Category VALUES ('67fff179-b6c3-4441-b997-28f3ff26177f', N'Phụ kiện')
INSERT dbo.Category VALUES ('79118eaa-05c6-40aa-989e-e471580d9cfd', N'Quần')
GO

USE ProductManagement
GO

IF DB_NAME() <> N'ProductManagement' SET NOEXEC ON
GO

--
-- Create foreign key [FK_Product_CategoryID_Category] on table [dbo].[Product]
--
PRINT (N'Create foreign key [FK_Product_CategoryID_Category] on table [dbo].[Product]')
GO
ALTER TABLE dbo.Product
  ADD CONSTRAINT FK_Product_CategoryID_Category FOREIGN KEY (CategoryID) REFERENCES dbo.Category (ID)
GO
SET NOEXEC OFF
GO